/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fm0decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(61a525b12d930325a7c2c58b8f2f7cf5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/myc/fm0decoder.h>
// pydoc.h is automatically generated in the build directory
#include <fm0decoder_pydoc.h>

void bind_fm0decoder(py::module& m)
{

    using fm0decoder = gr::myc::fm0decoder;


    py::class_<fm0decoder, gr::sync_decimator, std::shared_ptr<fm0decoder>>(
        m, "fm0decoder", D(fm0decoder))

        .def(py::init(&fm0decoder::make), D(fm0decoder, make))


        ;
}
